class ColumnOption {
  final String mapKey;
  final String mapName;
  final String selectorName;
  final String headerName;
  final double portraitWidth;
  final double landscapeWidth;

  ColumnOption(
    this.mapKey,
    this.mapName,
    this.selectorName,
    this.headerName,
    this.portraitWidth,
    this.landscapeWidth,
  );

  // Computed property to get the index based on the list position
  int getIndex(List<ColumnOption> list) {
    return list.indexOf(this);
  }
}

final List<ColumnOption> kAllColumns = [
  ColumnOption('EFFICIENCY', 'PLAYER', 'PLAYER', 'PLAYER', 0.35, 0.15),
  ColumnOption('EFFICIENCY', 'TEAM', 'TEAM', 'TEAM', 0.135, 0.06),
  ColumnOption('EFFICIENCY', 'AGE', 'AGE', 'AGE', 0.1, 0.04),
  ColumnOption('EFFICIENCY', 'POSITION', 'POSITION', 'POS', 0.1, 0.04),
  ColumnOption('EFFICIENCY', 'GP', 'GAMES PLAYED', 'GP', 0.12, 0.04),
  ColumnOption('EFFICIENCY', 'MIN', 'MINUTES', 'MIN', 0.12, 0.04),
  ColumnOption('EFFICIENCY', 'MPG', 'MIN PER GM', 'MPG', 0.12, 0.04),
  ColumnOption('EFFICIENCY', 'POSS', 'POSSESSIONS', 'POSS', 0.12, 0.04),
  ColumnOption('EFFICIENCY', 'POSS PER GM', 'POSS PER GM', 'PSPG', 0.12, 0.04),
  ColumnOption('EFFICIENCY', 'PPG', 'PPG', 'PPG', 0.13, 0.05),
  ColumnOption('EFFICIENCY', 'RPG', 'RPG', 'RPG', 0.11, 0.04),
  ColumnOption('EFFICIENCY', 'APG', 'APG', 'APG', 0.11, 0.04),
  ColumnOption('EFFICIENCY', 'SPG', 'SPG', 'SPG', 0.11, 0.04),
  ColumnOption('EFFICIENCY', 'BPG', 'BPG', 'BPG', 0.11, 0.04),
  ColumnOption('EFFICIENCY', 'TOPG', 'TOPG', 'TOPG', 0.11, 0.04),
  ColumnOption('SCORING', 'FGM', 'FGM', 'FGM', 0.11, 0.04),
  ColumnOption('SCORING', 'FGA', 'FGA', 'FGA', 0.11, 0.04),
  ColumnOption('SCORING', 'FG%', 'FG%', 'FG%', 0.13, 0.045),
  ColumnOption('SCORING', '3PM', '3PM', '3PM', 0.11, 0.04),
  ColumnOption('SCORING', '3PA', '3PA', '3PA', 0.11, 0.04),
  ColumnOption('SCORING', '3P%', '3P%', '3P%', 0.13, 0.045),
  ColumnOption('CLOSEST DEFENDER', 'WIDE OPEN 3P%', 'WIDE OPEN 3P%', 'WO 3P%', 0.15, 0.05),
  ColumnOption('SCORING', '3PA RATE', '3PA RATE', '3PAr', 0.13, 0.05),
  ColumnOption('SCORING', 'FTM', 'FTM', 'FTM', 0.11, 0.04),
  ColumnOption('SCORING', 'FTA', 'FTA', 'FTA', 0.11, 0.04),
  ColumnOption('SCORING', 'FT%', 'FT%', 'FT%', 0.13, 0.045),
  ColumnOption('SCORING', 'FT/FGA', 'FT/FGA', 'FT/FGA', 0.13, 0.05),
  ColumnOption('SCORING', 'eFG%', 'EFG%', 'EFG%', 0.13, 0.05),
  ColumnOption('SCORING', 'TS%', 'TS%', 'TS%', 0.13, 0.05),
  ColumnOption('SCORING', '% UAST', '% UAST', '% UAST', 0.145, 0.05),
  ColumnOption('SCORING', '% 3P UAST', '% 3P UAST', '% 3UAST', 0.15, 0.05),
  ColumnOption('EFFICIENCY', 'USAGE', 'USAGE%', 'USG%', 0.13, 0.05),
  ColumnOption('EFFICIENCY', 'OFF LOAD', 'OFFENSIVE LOAD', 'LOAD%', 0.14, 0.05),
  ColumnOption('EFFICIENCY', 'C-TOV%', 'CREATION-BASED TOV %', 'C-TOV%', 0.15, 0.05),
  ColumnOption('EFFICIENCY', '+/-', '+/-', '+/-', 0.1, 0.04),
  ColumnOption('EFFICIENCY', 'NRTG', 'NET RATING ON/OFF', 'NRTG', 0.12, 0.04),
  ColumnOption('EFFICIENCY', 'ORTG', 'OFF RATING ON/OFF', 'ORTG', 0.12, 0.04),
  ColumnOption('EFFICIENCY', 'DRTG', 'DEF RATING ON/OFF', 'DRTG', 0.12, 0.04),
  ColumnOption('EFFICIENCY', 'TOUCHES', 'TOUCHES', 'TCH', 0.11, 0.04),
  ColumnOption('EFFICIENCY', 'TIME OF POSS', 'TIME OF POSSESSION', 'TOP', 0.11, 0.04),
  ColumnOption('EFFICIENCY', 'SECONDS PER TOUCH', 'SECONDS PER TOUCH', 'SEC', 0.11, 0.04),
  ColumnOption('EFFICIENCY', 'DRIBBLES PER TOUCH', 'DRIBBLES PER TOUCH', 'DRIB', 0.11, 0.04),
  ColumnOption('EFFICIENCY', '% SHOOT', '% SHOOT', '% SHOT', 0.145, 0.05),
  ColumnOption('EFFICIENCY', '% PASS', '% PASS', '% PASS', 0.145, 0.05),
  ColumnOption('EFFICIENCY', '% TOV', '% TURNOVER', '% TOV', 0.145, 0.05),
  ColumnOption('EFFICIENCY', '% FOULED', '% FOULED', '% FOUL', 0.145, 0.05),
  ColumnOption('REBOUNDING', 'REB', 'TOTAL REBOUNDS', 'REB', 0.125, 0.04),
  ColumnOption('REBOUNDING', 'OREB', 'OFF REBOUNDS', 'OREB', 0.12, 0.04),
  ColumnOption('REBOUNDING', 'OREB%', 'OFF REBOUND%', 'OREB%', 0.14, 0.05),
  ColumnOption('REBOUNDING', 'ADJ OREB CHANCE %', 'ADJ OREB CHANCE %', 'AORC%', 0.16, 0.05),
  ColumnOption('REBOUNDING', 'DREB', 'OFF REBOUNDS', 'DREB', 0.12, 0.04),
  ColumnOption('REBOUNDING', 'DREB%', 'DEF REBOUND %', 'DREB%', 0.14, 0.05),
  ColumnOption('REBOUNDING', 'ADJ DREB CHANCE %', 'ADJ DREB CHANCE %', 'ADRC%', 0.16, 0.05),
  ColumnOption('REBOUNDING', 'BOX OUTS', 'BOX OUTS', 'B-OUT', 0.125, 0.04),
  ColumnOption('PASSING', 'PASSES', 'PASSES MADE', 'PASS', 0.13, 0.05),
  ColumnOption('PASSING', 'AST%', 'AST%', 'AST%', 0.15, 0.05),
  ColumnOption('PASSING', '2ND AST', 'SECONDARY ASSIST', '2AST', 0.12, 0.04),
  ColumnOption('PASSING', 'FT AST', 'FT ASSIST', 'FT AST', 0.135, 0.05),
  ColumnOption('PASSING', 'ADJ AST', 'ADJ ASSIST', 'ADJ AST', 0.155, 0.05),
  ColumnOption('PASSING', 'BOX CREATION', 'BOX CREATION', 'BOX-C', 0.14, 0.05),
  ColumnOption('PASSING', 'POT. AST', 'POTENTIAL ASSIST', 'POT AST', 0.155, 0.05),
  ColumnOption('PASSING', 'AST PTS CREATED', 'ASSIST PTS CREATED', 'APC', 0.13, 0.05),
  ColumnOption('PASSING', 'AST-PASS %', 'AST - PASS %', 'A-P%', 0.13, 0.05),
  ColumnOption('PASSING', 'ADJ AST-PASS %', 'ADJ AST - PASS %', 'AA-P%', 0.135, 0.05),
  ColumnOption('DRIVES', 'DRIVES', 'DRIVES', 'DRV', 0.135, 0.05),
  ColumnOption('DRIVES', '% DRIVE', '% DRIVE', '% DRV', 0.135, 0.05),
  ColumnOption('DRIVES', 'PTS PER DRIVE', 'PTS PER DRIVE', 'PPD', 0.135, 0.05),
  ColumnOption('DRIVES', 'DRIVE FT/FGA', 'DRIVE FT/FGA', 'DRV FTr', 0.175, 0.06),
  ColumnOption('DRIVES', 'DRIVE FG%', 'DRIVE FG%', 'DRV FG%', 0.175, 0.06),
  ColumnOption('DRIVES', 'DRIVE TS%', 'DRIVE TS%', 'DRV TS%', 0.175, 0.06),
  ColumnOption('DRIVES', 'DRIVE PASS %', 'DRIVE PASS %', 'DRV PS%', 0.175, 0.06),
  ColumnOption('DRIVES', 'DRIVE AST %', 'DRIVE AST %', 'DRV AST%', 0.175, 0.06),
  ColumnOption('DRIVES', 'DRIVE TOV %', 'DRIVE TOV %', 'DRV TO%', 0.175, 0.06),
  ColumnOption('HUSTLE', 'DIST (MILES)', 'DISTANCE (MILES)', 'DIST', 0.155, 0.05),
  ColumnOption('HUSTLE', 'AVG SPEED', 'AVG SPEED', 'SPEED', 0.15, 0.045),
  ColumnOption('HUSTLE', 'SCREEN AST', 'SCREEN ASSISTS', 'SCN AST', 0.15, 0.045),
  ColumnOption('HUSTLE', 'SCREEN AST PTS', 'SCREEN AST PTS', 'SA PTS', 0.15, 0.045),
  ColumnOption('HUSTLE', 'FOULS', 'FOULS', 'PF', 0.11, 0.04),
  ColumnOption('HUSTLE', 'FOULS DRAWN', 'FOULS DRAWN', 'PFD', 0.11, 0.04),
  ColumnOption('HUSTLE', 'LOOSE BALLS', 'LOOSE BALLS RECOVERED', 'LB', 0.11, 0.04),
  ColumnOption('HUSTLE', 'CHARGES DRAWN', 'CHARGES DRAWN', 'CHRG', 0.11, 0.04),
  ColumnOption('DEFENSE', 'DRTG - ON', 'DEF RATING - ON COURT', 'DRTG-ON', 0.16, 0.06),
  ColumnOption('DEFENSE', 'VERSATILITY', 'VERSATILITY', 'VRS', 0.13, 0.04),
  ColumnOption('DEFENSE', 'MATCHUP DIFFICULTY', 'MATCHUP DIFFICULTY', 'MD', 0.13, 0.04),
  ColumnOption('DEFENSE', 'DEF IMPACT EST', 'DEF IMPACT ESTIMATE', 'DIE', 0.13, 0.04),
  ColumnOption('DEFENSE', 'DEFLECTS', 'DEFLECTIONS', 'DFLCT', 0.13, 0.04),
  ColumnOption('DEFENSE', 'CONTESTS', 'CONTESTED SHOTS', 'CNTST', 0.13, 0.04),
  // Add cols here (statGroup, statMapName, columnSelectName, headerName, width, index)
];
